FROM python:3.7

LABEL maintainer="Alvaro Cavalcanti <alvarovictor@gmail.com>"

RUN apt-get update

RUN mkdir /app

WORKDIR /app

COPY . /app

RUN pip install pip-tools

RUN pip-sync

ENV FLASK_ENV="docker"

EXPOSE 5000